### PR TITLE
Feature/show-music-events

### PR DESCRIPTION
**Pull request by AI-Pree**

### CODE REVIEW

**Comment by AI-Pree** [comment]
I need to filter the result from the search keyword provided  by the user and refactor the code a bit and add doc for the command.

**Comment by AI-Pree** [comment]
When its ready for pull i will update this branch to the develop

**Comment by AI-Pree** [comment]
@fisher60 I think its ready

**Comment by AI-Pree** [comment]
The response from the API is pretty ambiguous(for the user input keyword), so I need to add logic's to filter those results.

**Review by fisher60 — CHANGES_REQUESTED** [review]
Bot should send some sort of message to inform a user when the api request fails. I.e if you request an invalid band or there are no events, the bot should send a message that no events found.

**Review by fisher60 — APPROVED** [review]
Looks great, ty for changes.

**Pull request merged**
