### PR TITLE
Added clear text command

### PR DESCRIPTION
**Pull request by saiTama-max**
vester needed it and can be useful, if you want you can add permissions to use it as well to avoid misuse

### CODE REVIEW

**Comment by fisher60** [comment]
what is the need for this feature?

**Comment by saiTama-max** [comment]
to remove spammed messages quickly,
i just added it lol i dont think its too important

**Comment by ReneganRonin** [comment]
Coolio.

**Comment by fisher60** [comment]
I will not be merging this command at this time, maybe in the future we can look into it. I will make sure I label it for hacktober credit though

**Pull request closed without merging**
