### PR TITLE
Userinfo command

### PR DESCRIPTION
**Pull request by saiTama-max**
userinfo command in utilities cog, shows the basic info on the user in an embed, (intents should be enabled for the status to work)

### CODE REVIEW

**Comment by fisher60** [comment]
The docker build is failing as a result of the pipfile, so this is currently a breaking change.

**Comment by fisher60** [comment]
update: this is failing because the Pipfile.Lock needs to be updated. You should run `pipenv install` so that the Pipfile.lock will be updated.

**Review by fisher60 — CHANGES_REQUESTED** [review]
Overall, this is a really quality commit. Everything appears to be mostly working. 

There are two issues, however:

1. You need to `pipenv lock` to lock your dependencies (I believe this is correct, if it does not work, feel free to `pipenv install` in this scenario). And push the new pipfile.lock, this is so the docker container can deploy properly.

2. This change is dependent on emojis that all servers will not have. This bot is not meant only for out server, so it should have as few external dependencies as possible. 
Please consider alternatives to the emojis in the embed. Maybe there is a way to check if the server has the required emoji, if it does not it can use a default emoji or just a text representation.

I quite like the use of emojis here, so I would love to see the ability to confirm if the server has an emoji, or perhaps a command that adds the emojis to the server somehow?

**Comment by saiTama-max** [comment]
@fisher60 uhh so there were some messing up, so i will close this pr and then work directly on this repo

**Pull request closed without merging**
