### PR TITLE
Feature/randomcase

### PR DESCRIPTION
**Pull request by ReneganRonin**
**Just what the name implies 🍶**

### CODE REVIEW

**Comment by saiTama-max** [comment]
but then whats to_sponge for?

**Review by fisher60 — CHANGES_REQUESTED** [review]
please fix merge conflicts, you should be able to rebase hopefully. Mostly conflicts from linting.

**Comment by ReneganRonin** [comment]
> but then whats to_sponge for?
> 
> 

sponge is alternating, randomcase is random

**Review by fisher60 — APPROVED** [review]
This looks great, removed unnecessary comment. Fixed weather conflict errors from new branch. 

I also made some extra changes to weather, I am setting a bad example, haha.

**Pull request merged**
